name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  gi-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Documentation
        run: nix build . --print-build-logs

      - name: Set up Git configuration
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add the target repository
        run: |
          git remote add target-repo https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@github.com/halalgovra/halalgovra.github.io.git

      - name: Push to remote
        run: |
          cp -r result/libastal libastal
          git add libastal
          git commit -m "Deploy Reference"
          git push target-repo main:main  # Adjust the branch names as needed
