on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lints:
    name: Build
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: DeterminateSystems/nix-installer-action@main
    #   - run: nix build .

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Build Documentation
        run: |
          nix build . --print-build-logs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: result/libastal
